# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '32 11 * * 6'

permissions:
  contents: read

jobs:
  setup:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: setup
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build:
    name: Build
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        version: 
          - alpine:3.11
          - alpine:3.15
          - debian:11
    steps:
      - name: Build an image from Dockerfile
        run: |
          DIR=$(echo ${{matrix.version}} | sed -e 's,:,/,') && docker build -t ${{matrix.version}} ./baseimages/$DIR/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{matrix.version}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
